tmux set-option -g @thm_black "#000000"
tmux set-option -g @thm_bg "#192330"
tmux set-option -g @thm_grey "#71839b"
tmux set-option -g @thm_fg "#cdcecf"
tmux set-option -g @thm_red      '#c94f6d'
tmux set-option -g @thm_green    '#81b29a'
tmux set-option -g @thm_yellow   '#dbc074'
tmux set-option -g @thm_blue     '#719cd6'
tmux set-option -g @thm_purple   '#9d79d6'
tmux set-option -g @thm_aqua     '#63cdcf'
tmux set-option -g @thm_orange   '#f4a261'
tmux set-option -g @thm_light_grey "#aeafb0"
